### ISSUE TITLE
undefined reference to 'SSLv3_method

### ISSUE THREAD

**Issue by yannick** [huntlabs/collie#16]
trying to compile under archlinux i get
`../../../source/collie/bootstrap/serversslconfig.d:31: error: undefined reference to 'SSLv3_method'`
any ideas?

is there a way to use botan https://github.com/etcimon/botan/  ?

**Comment by dushibaiyu** [comment]
Now only used the openssl, you must has openssl‘s DLL。 I didn't use botan. 
frist, I will make SSL support to be optional,used the dub config.

**Comment by dushibaiyu** [comment]
Now you can only use the TCP without SSL support, and  see the "example/http/httpserver/dub.json" to enable SSL support.

**Comment by yannick** [comment]
i do have openssl.
the problem is `The SSLv3 protocol is deprecated and should not be used.`
and its not there anymore in recent openssl versions (and shoud not be used anyways)

see also http://www.libressl.org/patches.html

**Comment by dushibaiyu** [comment]
Thanks,I will fix it, use the botan.

And, I want to know which linux you used?
I use openSUSE 42.1, all is ok. in debian 8,SSLv3_method is undefined reference.

**Comment by dushibaiyu** [comment]
I see the libssl 2.3.4, the sslv2 is removed. Thank you.
and I has removed.

**Comment by yannick** [comment]
thanks. i was trying to use it under archlinux
