### ISSUE TITLE
dub test fails under OSX

### ISSUE THREAD

**Issue by ikod** [huntlabs/collie#32]
Hello,

When trying to run under OSX 10.11:

<pre>
Igors-MacBook-Pro:collie igor$ dub test
Generating test runner configuration '__test__library__' for 'library' (library).
Performing "unittest" build using dmd for x86_64.
collie 0.7.0: building configuration "__test__library__"...
source/collie/socket/acceptor.d(162,56): Error: undefined identifier '_inSocket'
source/collie/socket/eventloop.d(172,18): Error: no property 'timer' for type 'AsyncEvent*'
source/collie/socket/eventloop.d(177,29): Error: no property 'timer' for type 'AsyncEvent*'
source/collie/socket/eventloop.d(182,18): Error: no property 'timer' for type 'AsyncEvent*'
source/collie/socket/eventloop.d(254,23): Error: template instance collie.socket.eventloop.EventLoopImpl!(KqueueLoop) error instantiating
dmd failed with exit code 1.
</pre>

**Comment by dushibaiyu** [comment]
Thanks. now this erroe is fix.

**Comment by dushibaiyu** [comment]
but, now dub test have other problem， the examples is fine.

**Comment by dushibaiyu** [comment]
fix,it.now
