### ISSUE TITLE
removeAny unittest failing

### ISSUE THREAD

**Issue by cym13** [huntlabs/collie#34]
The following assert fails when doing “dub test” with DMDv2.071.1 on revision 6b2f1321fc5d0553f49741dd7809259276029894:

```
vec.removeAny(2);
assert(vec.dup == [15, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7]);
```

You can find the backtrace below:
## core.exception.AssertError@source/collie/utils/vector.d(282): unittest failure

??:? _d_unittest [0x819cbc4]
??:? void collie.utils.vector.__unittest_fail(int) [0x819aaac]
source/collie/utils/vector.d:248 void collie.utils.vector.__unittestL243_21() [0x8195d43]
??:? void collie.utils.vector.__modtest() [0x819aa47]
??:? int core.runtime.runModuleUnitTests().__foreachbody2(object.ModuleInfo_) [0x81ca470]
??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo_)).__lambda2(immutable(object.ModuleInfo_)) [0x819c4bc]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo_))).__foreachbody2(ref rt.sections_elf_shared.DSO) [0x81a414e]
??:? int rt.sections_elf_shared.DSO.opApply(scope int delegate(ref rt.sections_elf_shared.DSO)) [0x81a433f]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo_))) [0x81a40f3]
??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo_)) [0x819c4a0]
??:? runModuleUnitTests [0x81ca34b]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x81a03c4]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x81a036c]
??:? _d_run_main [0x81a02fe]
??:? main [0x815414b]
??:? __libc_start_main [0xb752f195]
Program exited with code 1

**Comment by dushibaiyu** [comment]
Thanks!
The code and unitest all error.
But , Now it is fixed.
